# Generated by Django 3.2.8 on 2021-12-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=16, unique=True)),
                ('client_data', models.CharField(max_length=155, unique=True)),
                ('client_name', models.CharField(max_length=155, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=55)),
                ('user_data', models.CharField(max_length=155, unique=True)),
                ('result_status', models.CharField(choices=[('INITIALIZED', 'INITIALIZED'), ('SELFIE', 'SELFIE'), ('FRONTSIDE', 'FRONTSIDE'), ('BACKSIDE', 'BACKSIDE'), ('RESULT', 'RESULT'), ('FINISHED', 'FINISHED')], default='INITIALIZED', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.client')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
                ('code', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.country')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documnet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.documenttype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.state')),
            ],
        ),
        migrations.CreateModel(
            name='ClientUserResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie_encodings', models.BinaryField(max_length=3000)),
                ('document_profile_pic_encodings', models.BinaryField(max_length=3000)),
                ('selfie_document_profile_pic_match_percentage', models.FloatField(default=0.0)),
                ('ocr_result_status', models.BooleanField(default=False)),
                ('kyc_number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.clientuser')),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.document'),
        ),
    ]
