# Generated by Django 3.2.8 on 2021-12-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0002_alter_clientuser_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='completed_users',
            field=models.IntegerField(default=0),
        ),
    ]
