# Generated by Django 3.2.8 on 2021-11-16 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_clientuserresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserresults',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='CORE.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientuserresults',
            name='kyc_number',
            field=models.CharField(max_length=20),
        ),
    ]
