# Generated by Django 3.2.8 on 2021-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0004_auto_20211116_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='country_code',
            field=models.CharField(default='IND', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientuser',
            name='document_type',
            field=models.CharField(default='LICENCE', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientuser',
            name='state_code',
            field=models.CharField(default='MH', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientuserresults',
            name='ocr_result_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientuserresults',
            name='selfie_document_profile_pic_match_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
